# Generated by Django 4.2.1 on 2023-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('phno', models.BigIntegerField(default=1)),
                ('photo', models.ImageField(default='', upload_to='seller/')),
                ('company_name', models.CharField(max_length=30)),
                ('ac_holder_name', models.CharField(default='', max_length=30)),
                ('ac_no', models.CharField(default='', max_length=30)),
                ('ifsc', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
    ]
